const resList = [
    {
      id: 1,
      restaurantName: "The Spicy Spoon",
      cuisine: ["Indian", "Chinese", "Fast Food"],
      rating: 4.5,
      deliveryTime: "30 mins",
      priceForTwo: "₹400 for two",
      offer: "50% off | Use code SPICY50",
      imageUrl: "https://imgs.search.brave.com/ND_1NJfNsltaADvBATPTEAJVDvMIVB-l1rfqVZinP2U/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzAz/NjAvMzA3MC85OTAw/L3QvMy9hc3NldHMv/NTc4MGM5MTZhYWVl/LS1BbWVyaWNhbi1T/cG9vbi1BdWcyMDE5/Njg1NTcuSlBHP3Y9/MTcyNTU2Nzc0Ng",
      isVeg: true,
      distance: "2.5 km away",
      tags: ["Great Discounts", "Recommended", "Best Seller"],
    },
    {
      id: 2,
      restaurantName: "Pizza Paradise",
      cuisine: ["Italian", "Pizza"],
      rating: 4.2,
      deliveryTime: "25 mins",
      priceForTwo: "₹600 for two",
      offer: "Buy 1 Get 1 Free",
      imageUrl: "https://imgs.search.brave.com/wa2dwzo-cAz0OC7FDsFioUBHBpkx9VUHSoDZW8Wcc7c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuc3BvdGFwcHMu/Y28vc3BvdHMvMjgv/NzViNzViNGZhNjQz/ZmRiYzA3MjQ1NjA4/NmIxYjE3L2Z1bGw",
      isVeg: false,
      distance: "1.8 km away",
      tags: ["Trending", "Top Rated", "Quick Delivery"],
    },
    {
      id: 3,
      restaurantName: "Burger Blast",
      cuisine: ["American", "Fast Food"],
      rating: 4.1,
      deliveryTime: "20 mins",
      priceForTwo: "₹350 for two",
      offer: "20% off on orders above ₹300",
      imageUrl: "https://via.placeholder.com/400x300",
      isVeg: false,
      distance: "3.2 km away",
      tags: ["Best Seller", "Great Discounts"],
    },
    {
      id: 4,
      restaurantName: "Healthy Bites",
      cuisine: ["Salads", "Healthy", "Continental"],
      rating: 4.7,
      deliveryTime: "35 mins",
      priceForTwo: "₹500 for two",
      offer: "Free dessert on orders above ₹500",
      imageUrl: "https://via.placeholder.com/400x300",
      isVeg: true,
      distance: "4.0 km away",
      tags: ["Healthy Choices", "Recommended"],
    },
    {
      id: 5,
      restaurantName: "Tandoori Treats",
      cuisine: ["Indian", "Tandoor", "Barbecue"],
      rating: 4.3,
      deliveryTime: "40 mins",
      priceForTwo: "₹450 for two",
      offer: "Flat ₹100 off | Use code TANDOORI100",
      imageUrl: "https://via.placeholder.com/400x300",
      isVeg: false,
      distance: "5 km away",
      tags: ["Spicy Delights", "Chef's Special"],
    },
    {
      id: 6,
      restaurantName: "Sushi Central",
      cuisine: ["Japanese", "Sushi", "Asian"],
      rating: 4.8,
      deliveryTime: "45 mins",
      priceForTwo: "₹800 for two",
      offer: "Free drink with every Sushi platter",
      imageUrl: "https://via.placeholder.com/400x300",
      isVeg: false,
      distance: "3.5 km away",
      tags: ["Exotic Flavors", "Top Rated"],
    },
    {
        id: 7,
        restaurantName: "Sushi",
        cuisine: ["Japanese", "Sushi", "Asian"],
        rating: 3.8,
        deliveryTime: "45 mins",
        priceForTwo: "₹800 for two",
        offer: "Free drink with every Sushi platter",
        imageUrl: "https://via.placeholder.com/400x300",
        isVeg: false,
        distance: "3.5 km away",
        tags: ["Exotic Flavors", "Top Rated"],
      },{
        id: 8,
        restaurantName: "Central",
        cuisine: ["Japanese", "Sushi", "Asian"],
        rating: 4,
        deliveryTime: "45 mins",
        priceForTwo: "₹800 for two",
        offer: "Free drink with every Sushi platter",
        imageUrl: "https://via.placeholder.com/400x300",
        isVeg: false,
        distance: "3.5 km away",
        tags: ["Exotic Flavors", "Top Rated"],
      },{
        id: 9,
        restaurantName: "Sushi Central",
        cuisine: ["Japanese", "Sushi", "Asian"],
        rating: 3,
        deliveryTime: "45 mins",
        priceForTwo: "₹800 for two",
        offer: "Free drink with every Sushi platter",
        imageUrl: "https://via.placeholder.com/400x300",
        isVeg: false,
        distance: "3.5 km away",
        tags: ["Exotic Flavors", "Top Rated"],
      },
  ];

export default resList